//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Linq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class videoclubEntities : DbContext
    {
        public videoclubEntities()
            : base("name=videoclubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquileres> alquileres { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<estilos> estilos { get; set; }
        public virtual DbSet<peliculas> peliculas { get; set; }
        public virtual DbSet<socios> socios { get; set; }
    }
}
