//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class peliculas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public peliculas()
        {
            this.alquileres = new HashSet<alquileres>();
        }
    
        public int codpeli { get; set; }
        public string titulo { get; set; }
        public string director { get; set; }
        public string protagonista { get; set; }
        public string argumento { get; set; }
        public string estilo { get; set; }
        public Nullable<int> anio { get; set; }
        public byte[] caratula { get; set; }
        public string categoria { get; set; }
        public Nullable<int> stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquileres> alquileres { get; set; }
        public virtual categorias categorias { get; set; }
        public virtual estilos estilos { get; set; }
    }
}
