//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instalador
{
    using System;
    using System.Collections.Generic;
    
    public partial class PISTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PISTAS()
        {
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public int Id_pista { get; set; }
        public string Nombre { get; set; }
        public int Aforo { get; set; }
        public byte[] Foto { get; set; }
        public int Deporte { get; set; }
    
        public virtual DEPORTES DEPORTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
    }
}
