//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instalador
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        public int Id_reserva { get; set; }
        public string Usuario { get; set; }
        public int Pista { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Franja { get; set; }
    
        public virtual FRANJAS_HORARIAS FRANJAS_HORARIAS { get; set; }
        public virtual PISTAS PISTAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
